[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
viaIR = true
optimizer = true
optimizer_runs = 200
remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
	"ds-test/=lib/solmate/lib/ds-test/src/",
	"erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
	"forge-std/=lib/forge-std/src/",
	"openzeppelin-contracts/=lib/openzeppelin-contracts/",
	"solmate/=lib/solmate/src/",
]

[rpc_endpoints]
base = "${BASE_URL}"
base_testnet = "${BASE_SEPOLIA_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api", chain = "8453" }
base_testnet = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api", chain = "84532" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
